
name: commerce_mvp
description: MVP app with provider
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.1

flutter:
  uses-material-design: true
