
name: commerce_mvp
description: MVP app with provider
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.2
  flutter_pdfview: ^1.4.5
  http: ^1.6.0
  path_provider: ^2.1.6
  pdf: ^3.12.0
  qr_flutter: ^4.1.0

flutter:
  uses-material-design: true
